### ISSUE TITLE
Local variables tracking

### ISSUE THREAD

**Issue by yann300** [ethdebug/format#42]
local variables (and params):
The compiler should if possible returns all the ranges in the VM trace where a specific local is in the scope, and how to track its ref or value in the stack (this is perhaps the most important thing for us or at least this is where we spent most of the time..)

**Comment by gnidan** [comment]
For this, I imagine something like this pair of instruction annotations (note the use of `parent` as an example, to indicate how scopes are re-used/inherited):

```yaml
operation:
  begin: scope
  id: 5
  parent: 4
  variables:
    x:
      type:
        kind: uint
        bits: 256
```

Then, later another instruction would be annotated with something like:

```yaml
operation:
  scope: deallocate
  variables: ["x"]
```
