### ISSUE TITLE
Improve encoding of the sourcemaps

### ISSUE THREAD

**Issue by yann300** [ethdebug/format#43]
It would make sense to wrap it in a different object that would make the integration with other tooling easier...

**Comment by gnidan** [comment]
How about:
```yaml
operation:
  begin: source-range
  file: 6
  start: 60
  length: 100
```
